[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{access = "write", path = "./reports"}]

solc = "0.8.20"
evm_version = "paris"
via_ir = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config